export const portfolioContent = {
  profile: {
    initials: "NS",
    name: "Nitesh Sahu",
    eyebrow: "I build scalable web apps and AI solutions.",
    role: "Building AI-Powered Web Applications",
    headline: "AI & Web Apps",
    summary:
      "Computer Science undergraduate and GDG Lead at SSIPMT Raipur passionate about building scalable web applications and AI-powered solutions.",
    supportUrl: "mailto:iamniteshsahu20@gmail.com",
    githubUrl: "https://github.com/nitesh-20",
    cityImage: "/assets/city.jpg",
    portraitImage: "/assets/profile.jpeg",
    voiceIntro:
      "Hey, I am Nitesh Sahu. I am a Computer Science student and the Google Developer Groups student lead. I build scalable web applications and AI-powered solutions.",
  },
  navigation: [
    { label: "Work", href: "#experience" },
    { label: "GitHub", href: "#github-sync" },
    { label: "About", href: "#about" },
    { label: "Stack", href: "#stack" },
    { label: "Wins", href: "#achievements" },
    { label: "Projects", href: "#projects" },
  ],
  socialLinks: [
    {
      label: "GitHub",
      handle: "@nitesh-20",
      href: "https://github.com/nitesh-20",
      icon: "/assets/icons/github.svg",
      tone: "",
    },
    {
      label: "LinkedIn",
      handle: "connect",
      href: "https://www.linkedin.com/in/niteshsahu20/",
      icon: "/assets/icons/linkedin.svg",
      tone: "linkedin",
    },
    {
      label: "X",
      handle: "@Niteshsahu2001",
      href: "https://x.com/Niteshsahu2001",
      icon: "/assets/icons/x.svg",
      tone: "x",
    },
  ],
  experience: [

    {
      title: "GDG Lead",
      company: "SSIPMT Raipur",
      meta: ["2025 - Present", "Raipur, Chhattisgarh, India"],
      description:
        "Leading the Google Developer Groups (GDG) student community at SSIPMT Raipur. Organizing technical workshops, hackathons, coding competitions, and developer events. Mentoring students in Web Development, Cloud Computing, AI, and Open Source. Collaborating with industry professionals to drive technical initiatives.",
      icon: "/assets/icons/gdg.svg?v=2",
      tone: "gdg",
      tags: ["Leadership", "Community", "Web Dev", "Cloud", "AI"],
    },
    {
      title: "Web Developer Intern",
      company: "Internship Studio",
      meta: ["May 28, 2024 – July 2, 2024", "Remote"],
      description: [
        "Designed and developed responsive web pages using HTML, CSS, and JavaScript.",
        "Enhanced website functionality and user experience by integrating modern frontend technologies like React.js and Tailwind CSS.",
        "Gained practical experience in building and optimizing web interfaces.",
      ],
      icon: "/assets/icons/briefcase.svg?v=2",
      tone: "",
      tags: ["HTML", "CSS", "JavaScript", "React.js", "Tailwind CSS"],
    },
  ],
  about: [
    "I am a Computer Science undergraduate and the GDG Lead at SSIPMT Raipur, deeply passionate about building scalable web applications and AI-powered solutions.",
    "Experienced in developing real-world projects across diverse domains including Agriculture, Legal Tech, and FinTech.",
    "Strong focus on backend engineering, cloud technologies, intelligent systems, and AI-powered application development.",
    "Recognized for competitive technical achievements, including being a Google Build Blog Marathon Winner and Google Cloud Agentic AI Day Finalist.",
  ],
  stackGroups: [
    {
      title: "Languages",
      items: ["JavaScript", "C++", "SQL"],
    },
    {
      title: "Frontend",
      items: ["React.js", "TypeScript", "HTML5", "CSS3"],
    },
    {
      title: "Backend & Databases",
      items: ["Node.js", "Express.js", "REST APIs", "MVC Architecture", "MySQL", "Firebase Firestore"],
    },
    {
      title: "Cloud & AI Tools",
      items: ["Google Cloud Platform (GCP)", "Firebase", "RAG", "LLMs", "Gemini", "Git", "GitHub", "Postman", "VS Code"],
    },
  ],
  achievements: [
    {
      number: "01",
      title: "Google Build Blog Marathon 2025",
      badge: "Winner",
      badgeTone: "green",
      org: "Google",
      year: "2025",
      icon: "/assets/icons/google.svg",
      iconTone: "google",
    },
    {
      number: "02",
      title: "Google Cloud Agentic AI Day 2025",
      badge: "Finalist",
      badgeTone: "blue",
      org: "Google Cloud",
      year: "2025",
      icon: "/assets/icons/gcp.svg",
      iconTone: "gcp",
    },
    {
      number: "03",
      title: "Paytm Hackathon 2026",
      badge: "Finalist",
      badgeTone: "blue",
      org: "Paytm",
      year: "2026",
      icon: "/assets/icons/paytm.svg",
      iconTone: "paytm",
    },
    {
      number: "04",
      title: "East India Blockchain Hackathon",
      badge: "Finalist",
      badgeTone: "blue",
      org: "IIT Kharagpur",
      year: "2025",
      icon: "/assets/icons/blockchain.svg",
      iconTone: "blockchain",
    },
    {
      number: "05",
      title: "ESG Invest Hackathon",
      badge: "4th Rank",
      badgeTone: "blue",
      org: "IIT Bombay",
      year: "2025",
      icon: "/assets/icons/iit.svg",
      iconTone: "iit",
    },
  ],
  projects: [
     {
      name: "RIO",
      href: "https://github.com/nitesh-20/Regulatory-Intelligence-OS-RIO-",
      liveLink: "https://rio-agent-platform.vercel.app/",
      kind: "AI Regulatory Assistant · React.js + TypeScript + FastAPI + GCP",
      summary: "AI-powered platform that simplifies regulatory research by helping users search, analyze, and understand complex regulatory documents.",
      description:
        "RIO (Regulatory Intelligence Operating System) is an AI-powered platform that transforms complex regulatory documents into an intelligent, searchable knowledge base. Using LLMs, Retrieval-Augmented Generation (RAG), and semantic search, it enables users to ask natural language questions and receive accurate, context-aware responses, significantly reducing the time required for regulatory research.",
      icon: "/assets/icons/rio.svg?v=2",
      built: [
        "Built an AI-powered regulatory intelligence platform for efficient document search and analysis.",
        "Implemented Retrieval-Augmented Generation (RAG) to provide context-aware answers from regulatory documents.",
        "Enabled semantic search for faster retrieval of relevant regulations and compliance information.",
        "Developed an intuitive interface for querying regulations using natural language.",
        "Designed scalable document ingestion and indexing pipelines for efficient information retrieval.",
        "Improved research productivity by reducing manual document review and accelerating compliance workflows.",
      ],
      challenge: [],
      tags: ["React.js", "TypeScript", "FastAPI", "RAG", "Vector Search", "LLMs", "Firebase", "Legal Tech"],
      defaultOpen: false,
    },
    {
      name: "LawGPT",
      href: "https://github.com/nitesh-20/LawGptGoogle",
      liveLink: "https://law-gpt-1c925.firebaseapp.com/",
      kind: "AI Legal Assistant · React.js + Node.js + Express.js + MySQL",
      summary: "Developed an AI-powered legal document analysis and question-answering platform.",
      description:
        "LawGPT is an AI assistant designed to streamline legal research workflows. It implements Retrieval-Augmented Generation (RAG) with vector search to enable semantic search and contextual querying across legal PDF documents, improving information retrieval speed and accuracy.",
      icon: "/assets/icons/lawgpt.svg",
      built: [
        "Developed an AI-powered legal document analysis and question-answering platform.",
        "Implemented Retrieval-Augmented Generation (RAG) with vector search.",
        "Enabled semantic search and contextual querying across legal PDFs.",
        "Improved information retrieval accuracy for legal research workflows.",
      ],
      challenge: [],
      tags: ["React.js", "Node.js", "Express.js", "MySQL", "RAG", "Vector Search", "LLMs", "Legal Tech"],
      defaultOpen: true,
    },
    {
      name: "Vaani.AI",
      href: "https://github.com/nitesh-20/Vaani-Ai-for-Paytm",
      liveLink: "https://vaani-ai-paytm.vercel.app/",
      kind: "Voice AI for Merchant Intelligence · React.js + Node.js + Gemini",
      summary: "Voice-first AI assistant helping merchants understand settlements, deductions, and transaction insights.",
      description:
        "Vaani.AI is a voice-first assistant built for merchants to check settlements and transaction data contextually. It integrates Gemini and transaction-aware RAG-based workflows to resolve merchant queries instantly.",
      icon: "/assets/icons/vaani.svg",
      built: [
        "Built a voice-first AI assistant helping merchants understand settlements, deductions, and transaction insights.",
        "Developed a transaction-aware RAG system for contextual financial query resolution.",
        "Integrated Gemini and RAG-based workflows for contextual financial query resolution.",
        "Recognized as a Finalist project at Paytm Hackathon 2026.",
      ],
      challenge: [],
      tags: ["React.js", "Node.js", "Gemini", "RAG", "Voice AI", "Paytm Hackathon", "FinTech"],
      defaultOpen: false,
    },
    {
      name: "Agrisahayak",
      href: "https://github.com/nitesh-20/Google-AgenticAi-Hackthon",
      liveLink: "https://google-agentic-ai-hackthon.vercel.app/",
      kind: "AI Agriculture Assistant · React.js + GCP + Firebase",
      summary: "AI-powered platform providing crop guidance, weather alerts, and market intelligence.",
      description:
        "Agrisahayak is a localized agricultural assistance platform. It leverages AI to guide farmers on crop selection, provides weather alerts and market intelligence, and integrates cloud-based recommendation systems for decision-making.",
      icon: "/assets/icons/agrisahayak.svg",
      built: [
        "Built an AI-powered platform providing crop guidance, weather alerts, and market intelligence.",
        "Integrated cloud-based recommendation systems to assist farmers in decision-making.",
        "Focused on accessibility and real-time agricultural insights for rural users.",
        "Recognized as a Finalist project at Google Cloud Agentic AI Day 2025.",
      ],
      challenge: [],
      tags: ["React.js", "GCP", "Firebase", "Recommendation Systems", "Agriculture", "Agentic AI"],
      defaultOpen: false,
    },
  ],
  quickActions: [
    { label: "Jump to Home", href: "#home" },
    { label: "Jump to Work Experience", href: "#experience" },
    { label: "Jump to GitHub Sync", href: "#github-sync" },
    { label: "Jump to About", href: "#about" },
    { label: "Jump to Stack", href: "#stack" },
    { label: "Jump to Achievements", href: "#achievements" },
    { label: "Jump to Projects", href: "#projects" },
  ],
  copyActions: [
    { label: "Copy GitHub URL", value: "https://github.com/nitesh-20" },
    { label: "Copy LinkedIn URL", value: "https://www.linkedin.com/in/niteshsahu20/" },
    { label: "Copy X URL", value: "https://x.com/Niteshsahu2001" },
  ],
} as const;

export type PortfolioContent = typeof portfolioContent;
