export const portfolioContent = {
  profile: {
    initials: "NS",
    name: "Nitesh Sahu",
    location: "Bengaluru, Karnataka",
    phone: "+91 9755175246",
    email: "iamniteshsahu20@gmail.com",
    eyebrow: "AI Systems & Full-Stack Engineer",
    role: "Specializing in Production LLM Infrastructure, Voice AI & Multi-Agent Workflows",
    headline: "AI Systems & Full-Stack",
    summary:
      "AI Systems & Full-Stack Engineer specializing in production LLM infrastructure, real-time Voice AI, and autonomous multi-agent workflows. Hands-on experience in architecting full-stack software and fail-safe AI pipelines across fintech, legaltech, and regtech. Recognized across 5+ national hackathons for building production-grade software solutions.",
    supportUrl: "mailto:iamniteshsahu20@gmail.com",
    githubUrl: "https://github.com/nitesh-20",
    linkedinUrl: "https://www.linkedin.com/in/niteshsahu20/",
    resumeUrl: "/Nitesh.pdf",
    cityImage: "/assets/city.jpg",
    portraitImage: "/assets/profile.jpeg",
    voiceIntro:
      "Hey, I am Nitesh Sahu. I am an AI Systems & Full-Stack Engineer and GDG Lead. I specialize in production LLM infrastructure, real-time Voice AI, and autonomous multi-agent workflows.",
  },
  navigation: [
    { label: "Experience", href: "#experience" },
    { label: "Projects", href: "#projects" },
    { label: "Achievements", href: "#achievements" },
    { label: "Tech Stack", href: "#stack" },
    { label: "Education", href: "#education" },
    { label: "About", href: "#about" },
    { label: "GitHub", href: "#github-sync" },
  ],
  socialLinks: [
    {
      label: "GitHub",
      handle: "@nitesh-20",
      href: "https://github.com/nitesh-20",
      icon: "/assets/icons/github.svg",
      tone: "",
    },
    {
      label: "LinkedIn",
      handle: "niteshsahu20",
      href: "https://www.linkedin.com/in/niteshsahu20/",
      icon: "/assets/icons/linkedin.svg",
      tone: "linkedin",
    },
    {
      label: "Email",
      handle: "iamniteshsahu20@gmail.com",
      href: "mailto:iamniteshsahu20@gmail.com",
      icon: "/assets/icons/gcp.svg",
      tone: "google",
    },
  ],
  education: {
    institution: "Chhattisgarh Swami Vivekanand Technical University",
    location: "Bhilai, Chhattisgarh",
    degree: "Bachelor of Technology in Computer Science",
    duration: "2023 – 2027",
    highlights: [
      "Specialization in Computer Science & AI Systems",
      "GDG Lead at SSIPMT Raipur running workshops on Agentic AI and Full-Stack Engineering",
      "5+ National Hackathon winner & finalist",
    ],
  },
  experience: [
    {
      title: "GDG Lead",
      company: "GDG on Campus SSIPMT Raipur",
      meta: ["Jul 2025 – Present", "Raipur, Chhattisgarh, India"],
      description: [
        "Led community of 500+ developers; organized technical workshops on Agentic AI, Cloud, and Full-Stack development.",
        "Led hands-on workshops on Gemini API, Firebase, React, and Google Cloud, mentoring students in AI application development and modern software engineering practices.",
      ],
      icon: "/assets/icons/gdg.svg?v=2",
      tone: "gdg",
      tags: ["Leadership", "Agentic AI", "Gemini API", "Google Cloud", "Firebase", "React"],
    },
    {
      title: "Full Stack Web Development Intern",
      company: "ElevanceSkills",
      meta: ["Jan 2026 – Jun 2026", "Remote · Bengaluru, Karnataka, India"],
      description: [
        "Developed scalable RESTful APIs using Node.js/Express with database query optimization under high concurrent requests.",
        "Implemented JWT authentication, role-based access control (RBAC), and IP rate limiting middleware to secure backend API routes.",
        "Automated API integration testing pipelines using Postman and GitHub Actions to maintain code reliability across releases.",
      ],
      icon: "/assets/icons/elevanceskills.svg",
      tone: "work",
      tags: [
        "Node.js",
        "Express.js",
        "JWT",
        "RBAC",
        "REST APIs",
        "Postman",
        "GitHub Actions",
        "Full-Stack",
      ],
    },
    {
      title: "Web Developer Intern",
      company: "Internship Studio",
      meta: ["May 2024 – Jul 2024", "Remote"],
      description: [
        "Developed reusable React.js components and responsive layouts using Tailwind CSS, standardizing cross-browser UI architecture.",
      ],
      icon: "/assets/icons/briefcase.svg?v=2",
      tone: "",
      tags: ["React.js", "Tailwind CSS", "JavaScript", "UI Architecture", "Cross-Browser"],
    },
  ],
  about: [
    "AI Systems & Full-Stack Engineer specializing in production LLM infrastructure, real-time Voice AI, and autonomous multi-agent workflows.",
    "Hands-on experience in architecting full-stack software and fail-safe AI pipelines across fintech, legaltech, and regtech domains.",
    "GDG Lead at SSIPMT Raipur, mentoring 500+ developers in Agentic AI, Gemini API, Cloud Native architecture, and modern full-stack development.",
    "Recognized across 5+ national hackathons including 1st place in Google Build & Blog Marathon 2025 and Finalist at Google Cloud Agentic AI Day 2025 & Paytm Hackathon 2026.",
  ],
  stackGroups: [
    {
      title: "Languages",
      items: ["Python", "TypeScript", "JavaScript", "C++", "Java (Basic)", "SQL"],
    },
    {
      title: "AI & LLM Systems",
      items: ["Multi-Agent Systems", "RAG Pipelines", "Real-Time Voice AI", "Vector DBs", "LangGraph", "Gemini Live API", "Qdrant", "ElevenLabs", "PydanticAI"],
    },
    {
      title: "Frameworks & Tools",
      items: ["FastAPI", "React 19", "Node.js", "Express.js", "Vue.js", "Next.js", "Tailwind CSS", "LiveKit", "ReportLab"],
    },
    {
      title: "Databases & Storage",
      items: ["PostgreSQL", "MySQL", "Firebase Firestore", "Redis"],
    },
    {
      title: "Cloud & Web Security",
      items: ["Docker", "Google Cloud Platform", "Git/GitHub", "REST APIs", "WebSockets", "JWT", "RBAC", "GitHub Actions"],
    },
  ],
  achievements: [
    {
      number: "01",
      title: "Google Build & Blog Marathon 2025",
      badge: "Winner",
      badgeTone: "green",
      org: "Google",
      year: "2025",
      description: "Selected 1st out of 200+ entries nationwide for authoring technical architecture article on advanced LLM systems.",
      icon: "/assets/icons/google.svg",
      iconTone: "google",
    },
    {
      number: "02",
      title: "Google Cloud Agentic AI Day 2025",
      badge: "Finalist",
      badgeTone: "blue",
      org: "Google Cloud",
      year: "2025",
      description: "Recognized among Top 15 teams nationwide for engineering enterprise agentic AI architectures.",
      icon: "/assets/icons/gcp.svg",
      iconTone: "gcp",
    },
    {
      number: "03",
      title: "Paytm Hackathon 2026",
      badge: "Finalist",
      badgeTone: "blue",
      org: "Paytm",
      year: "2026",
      description: "Shortlisted among 1,000+ teams for building real-time merchant voice AI interface with strict schema safety.",
      icon: "/assets/icons/paytm.svg",
      iconTone: "paytm",
    },
    {
      number: "04",
      title: "East India Blockchain Hackathon",
      badge: "Finalist",
      badgeTone: "blue",
      org: "IIT Kharagpur",
      year: "2025",
      description: "Engineered a decentralized peer-to-peer marketplace with smart contract execution.",
      icon: "/assets/icons/blockchain.svg",
      iconTone: "blockchain",
    },
    {
      number: "05",
      title: "ESG Invest Hackathon",
      badge: "4th Rank",
      badgeTone: "blue",
      org: "IIT Bombay",
      year: "2025",
      description: "Built and presented an ESG stock analysis platform to institutional judges.",
      icon: "/assets/icons/iit.svg",
      iconTone: "iit",
    },
  ],
  projects: [
    {
      name: "LawGPT",
      href: "https://github.com/nitesh-20/lawgpt-ai-os",
      liveLink: "https://lawgpt-os.vercel.app/",
      kind: "AI Legal Assistant · React + FastAPI + Qdrant + Gemini",
      summary: "AI legal research assistant with semantic chunking & vector search processing 100+ page legal documents.",
      description:
        "LawGPT is an AI-powered legal assistant built for fast, accurate legal research. It features semantic chunking and vector search in Qdrant for analyzing 100+ page complex legal documents, alongside an MCP-inspired multi-agent architecture with FastAPI, Firebase, and Gemini for intent routing and context-aware responses.",
      icon: "/assets/icons/lawgpt.svg",
      built: [
        "Built a legal research assistant using semantic chunking and vector search in Qdrant for processing 100+ page legal documents.",
        "Designed an MCP-inspired multi-agent architecture with FastAPI, Firebase, and Gemini for intent routing and context-aware responses.",
        "Engineered low-latency document indexing pipelines with PDF chunk parsing and metadata extraction.",
      ],
      challenge: [
        "Processing long multi-page legal documents without contextual loss.",
        "Routing user intent dynamically across specialized legal search agents.",
      ],
      tags: ["React", "FastAPI", "Python", "Firebase", "RAG", "Qdrant", "Google Gemini", "PDF Processing"],
      defaultOpen: true,
    },
    {
      name: "HirePilot AI",
      href: "https://github.com/nitesh-20/Hire-AI",
      kind: "AI Job Intelligence & Career Automation · Python + Gemini + PyYAML + ATS Ingestion",
      summary: "AI-powered job intelligence system discovering engineering roles, pre-filtering deterministically, & evaluating candidate fit using LLMs.",
      description:
        "HirePilot AI is an AI-powered job intelligence and career automation system built to reduce noise in job searching. It discovers opportunities across supported job platforms (Greenhouse, Lever, Ashby), applies zero-token deterministic filters for role, location, freshness, and experience, and evaluates candidate-job fit using LLMs to deliver focused daily HTML digests.",
      icon: "/assets/icons/hirepilot.svg",
      built: [
        "Built a multi-source job discovery pipeline ingesting public ATS job boards across Greenhouse, Lever, and Ashby APIs.",
        "Reduced thousands of raw postings to a candidate set using zero-token deterministic regex pre-filtering (title, location, max-age) before LLM inference.",
        "Engineered LLM-based candidate-job fit scoring with candidate profile parsing and early-career experience level constraints.",
        "Automated personalized HTML job digest generation and SMTP email delivery with local state deduplication tracking (seen.json).",
      ],
      challenge: [
        "Dropping ~99% of non-matching postings via metadata gates to minimize LLM token costs and throughput latency.",
        "Handling stateful deduplication across multiple ATS platforms to guarantee zero repeated job reviews.",
      ],
      tags: ["Python", "Google Gemini", "PyYAML", "Greenhouse", "Lever", "Ashby", "LLM Screening", "Job Automation"],
      defaultOpen: false,
    },
    {
      name: "Vaani AI",
      href: "https://github.com/nitesh-20/Vaani-Ai-for-Paytm",
      liveLink: "https://vaani-ai-paytm.vercel.app/",
      kind: "Real-Time Voice AI Agent · React 19 + FastAPI + Gemini Live API + LiveKit",
      summary: "Low-latency voice streaming agent for real-time merchant transaction verification.",
      description:
        "Vaani AI is a real-time, voice-first AI assistant built for instant merchant transaction queries and settlements. It features a low-latency voice streaming pipeline using LiveKit WebSockets, Gemini Live API, and ElevenLabs TTS audio I/O, coupled with strict payload schema validation for safe multi-step merchant actions.",
      icon: "/assets/icons/vaani.svg",
      built: [
        "Architected a low-latency voice streaming pipeline using LiveKit WebSockets, Gemini Live API, and ElevenLabs TTS for audio I/O.",
        "Built transaction verification voice workflows with strict payload schema validation to handle multi-step merchant actions safely.",
        "Integrated Deepgram STT for accurate multi-lingual speech transcription.",
      ],
      challenge: [
        "Maintaining sub-500ms end-to-end latency for streaming voice responses.",
        "Ensuring fail-safe execution for financial transaction verifications via strict JSON schemas.",
      ],
      tags: ["React 19", "FastAPI", "Gemini Live API", "LiveKit", "Deepgram STT", "ElevenLabs", "WebSockets"],
      defaultOpen: false,
    },
    {
      name: "Finance Copilot",
      href: "https://github.com/nitesh-20/Finance-Copilot",
      liveLink: "https://finance-copilot-kappa.vercel.app/",
      kind: "AI Equity Research Platform · Vue.js + FastAPI + PydanticAI + PostgreSQL",
      summary: "Multi-agent financial platform coordinating Bull/Bear/Judge agents for automated equity research.",
      description:
        "Finance Copilot is an AI-powered equity research platform that automates complex stock thesis generation. It features an Orchestrator coordinating Bull, Bear, and Judge multi-agent workflows, alongside resilient data ingestion pipelines (financial APIs with Yahoo Finance fallbacks) that produce structured PDF/HTML equity reports.",
      icon: "/assets/icons/sbi.svg",
      built: [
        "Architected a multi-agent financial platform with an Orchestrator coordinating Bull/Bear/Judge agents to automate stock thesis analysis.",
        "Built resilient data ingestion pipelines (financial APIs, Yahoo Finance fallbacks) generating structured PDF/HTML equity reports.",
        "Utilized PydanticAI and PostgreSQL for strictly typed agent output schemas and persistent thesis storage.",
      ],
      challenge: [
        "Synthesizing conflicting market arguments into an unbiased Judge decision.",
        "Ensuring graceful fallbacks across rate-limited market data APIs.",
      ],
      tags: ["Vue.js", "Tailwind CSS", "FastAPI", "Python", "PydanticAI", "OpenAI/Gemini", "PostgreSQL", "Docker", "ReportLab"],
      defaultOpen: false,
    },
    {
      name: "RIO",
      href: "https://github.com/nitesh-20/Regulatory-Intelligence-OS-RIO-",
      liveLink: "https://rio-agent-platform.vercel.app/",
      kind: "Regulatory Intelligence Operating System · React + LangGraph + PostgreSQL + Redis",
      summary: "Autonomous multi-agent regulatory monitor with structured audit logging & explainable traces.",
      description:
        "RIO (Regulatory Intelligence Operating System) is an autonomous multi-agent regulatory monitor designed for enterprise compliance reporting. Built using LangGraph, PostgreSQL, and Redis caching, it executes asynchronous regulatory impact analysis while providing structured audit logging and explainable decision traces.",
      icon: "/assets/icons/rio.svg?v=2",
      built: [
        "Built an autonomous multi-agent regulatory monitor using LangGraph, PostgreSQL, and Redis caching for asynchronous impact analysis.",
        "Implemented structured audit logging and explainable agent decision traces for enterprise compliance reporting.",
        "Designed real-time compliance alert dashboards with natural language document querying.",
      ],
      challenge: [
        "Orchestrating long-running stateful agent graphs across large regulatory policy updates.",
        "Providing deterministic audit traces for legal compliance compliance verification.",
      ],
      tags: ["React", "FastAPI", "Python", "LangGraph", "Gemini", "PostgreSQL", "Docker", "Redis"],
      defaultOpen: false,
    },
  ],
  quickActions: [
    { label: "Jump to Experience", href: "#experience" },
    { label: "Jump to Projects", href: "#projects" },
    { label: "Jump to Achievements", href: "#achievements" },
    { label: "Jump to Tech Stack", href: "#stack" },
    { label: "Jump to Education", href: "#education" },
    { label: "Jump to About", href: "#about" },
    { label: "Jump to GitHub Sync", href: "#github-sync" },
  ],
  copyActions: [
    { label: "Copy GitHub URL", value: "https://github.com/nitesh-20" },
    { label: "Copy LinkedIn URL", value: "https://www.linkedin.com/in/niteshsahu20/" },
    { label: "Copy Email", value: "iamniteshsahu20@gmail.com" },
    { label: "Copy Phone", value: "+919755175246" },
  ],
} as const;

export type PortfolioContent = typeof portfolioContent;
